### PR TITLE
Complete docs on require NodeBB modules

### PR DESCRIPTION
**Pull request by voanhcuoc**
https://github.com/NodeBB/NodeBB/issues/5255

### CODE REVIEW

**Comment by pitaj** [comment]
It is better to just use `require.main.require`

**Comment by voanhcuoc** [comment]
https://github.com/NodeBB/NodeBB/issues/5255#issuecomment-265022784

> When I use `mocha` for example, `require.main` would be something like `./node_modules/mocha/bin/_mocha.`

**Comment by julianlam** [comment]
Both usages are fine and have their advantages. I personally don't advocate one over the other.

**Comment by voanhcuoc** [comment]
I placed `require.main.require` first as it's the easier way.
Merge ?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/docs/commit/fc148c0e5c739b3aca15fd861fa6f42a15e30d4f

**Pull request closed without merging**
